/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gprinter_utils_SerialPortControl */

#ifndef _Included_com_gprinter_utils_SerialPortControl
#define _Included_com_gprinter_utils_SerialPortControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gprinter_utils_SerialPortControl
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_gprinter_utils_SerialPortControl_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_gprinter_utils_SerialPortControl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gprinter_utils_SerialPortControl_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
